@startuml
class Window {
  + RMCSX x_size
  + RMCSX x_centre
  + RMCSY y_size
  + RMCSY y_centre
}

class SomePosition {
  + double position
}

Client --> ScanParameters : specifies >
Client --> StepParameters : specifies >
ScanParameters *--> Frame
StepParameters *--> Frame

Frame *--> Window

Frame *--> “0..1” Somehting : might contain >

Frame --> SomePosition : converted to >
SomePosition --> SomePeripheral : applied to >
SomePosition --> SomeBalanceMass : influences > 


@enduml
